### ISSUE TITLE
Use a proper logging framework

### ISSUE THREAD

**Issue by thomaseizinger** [coblox/bobtimus#17]
Using a proper logging framework for bobtimus. `log4js` or something? `debug` is _quite_ limited because it doesn't even have log levels.

_Originally posted by @thomaseizinger in https://github.com/coblox/bobtimus/pull/14_

Note: `error` level logs will trigger a notification. Hence, the following need to be error level:
  - no/low funds
  - comit-rs/btsieve/blockchain node are unreachable
  - trade failed
Log framework: up to the implementer.

**Comment by da-kami** [comment]
Apparently the refactoring and changes of bobtimus/#45 are so extensive that it would have been better to wait with starting this task. I will put it on hold until bobtimus/#45 has been merged.
