### ISSUE TITLE
Testnet setup & deployment

### ISSUE THREAD

**Issue by D4nte** [coblox/bobtimus#44]
When picking up this issue, ping @bonomat to do #48

Setup the following on a fresh (Google Cloud Ubuntu) machine:
 - bobtimus: git checkout && node-ts
 - makeshift: use `master` (not blocking)
 - comit-rs: manual deployment, use `master`
 - blockchains: bitcoind (testnet) & parity (ropsten), no docker
 - monitoring solution: https://cloud.google.com/monitoring/
    - follow-up ticket for bobtimus: #74

Note: use systemd/services to make life easier

**Comment by bonomat** [comment]
Useful links for logging: 
- How to get application logs into Stackdriver on the example of bitcoind:
   https://medium.com/google-cloud/how-to-log-your-application-on-google-compute-engine-6600d81e70e3

**Comment by D4nte** [comment]
Open port 80 and we are done :)

**Comment by bonomat** [comment]
yes, done, bobtimus errors are now reported to our slack
