### ISSUE TITLE
Market making rate & link creation

### ISSUE THREAD

**Issue by D4nte** [coblox/bobtimus#45]
To avoid issues with funds, Bobtimus needs to calculate:
- an acceptable rate
- a published rate (link)
- a maximum acceptable amounts
- a published amounts (link)
Each time Bobtimus does the funding action (remember the option problem).
Which means that a unique ID should be generated for a new rate each time a fund is done.

When rates/amounts are updated, a new link should be created and put it in a html file.

The **published amount** is `min(ether_balance/i, bitcoin_balance/i)`.
Where `i` is configurable or calculated on the same curve than the rates (up to implementer).

The **acceptable rate** is the published minus some margin to allow old links to still be valid for some times (but not forever).
Similarly for the **acceptable amount**.

**Comment by thomaseizinger** [comment]
Done in #56.

Remaining glue to be written as part of https://github.com/coblox/bobtimus/issues/46.
