### ISSUE TITLE
Make Bobtimus testnet ready

### ISSUE THREAD

**Issue by D4nte** [coblox/bobtimus#59]
Start Bobtimus against testnet blockchain nodes to iron out the bugs.

Be sure to test:
- both direction swaps eth->btc & btc->eth
- including refund scenario from both comit-i and bobtimus
- confirms it declines ERC20 swap requests (shown in #70)

**Comment by D4nte** [comment]
@thomaseizinger done?

**Comment by bonomat** [comment]
We never did the refund part though, but swapping worked in both directions.

**Comment by D4nte** [comment]
Hum, need to test refund then :)

**Comment by thomaseizinger** [comment]
Assuming this is done because it is running on testnet :D
