### ISSUE TITLE
Get some ERC20 tokens for bobtimus on testnet

### ISSUE THREAD

**Issue by thomaseizinger** [coblox/bobtimus#82]
Talk to Toby.

**Comment by bonomat** [comment]
@D4nte : has this been resolved?

**Comment by D4nte** [comment]
Yes

**Comment by D4nte** [comment]
https://rinkeby.etherscan.io/tx/0x91fd4caee5c78e3f224bb75a36e93542c21fa5d7b27a8f5f3ec3df60a7a5fd1c

https://rinkeby.etherscan.io/address/0xF5d49387EcFA36bD2BF047d9E72344A2b3afBB72
